// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: deposit.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WithdrawalStatus int32

const (
	WithdrawalStatus_WITHDRAWAL_STATUS_UNSPECIFIED WithdrawalStatus = 0
	WithdrawalStatus_WITHDRAWAL_STATUS_PENDING     WithdrawalStatus = 1
	WithdrawalStatus_WITHDRAWAL_STATUS_PROCESSING  WithdrawalStatus = 2
	WithdrawalStatus_WITHDRAWAL_STATUS_PROCESSED   WithdrawalStatus = 3
	WithdrawalStatus_WITHDRAWAL_STATUS_FAILED      WithdrawalStatus = 4
	WithdrawalStatus_WITHDRAWAL_STATUS_INVALID     WithdrawalStatus = 5
)

// Enum value maps for WithdrawalStatus.
var (
	WithdrawalStatus_name = map[int32]string{
		0: "WITHDRAWAL_STATUS_UNSPECIFIED",
		1: "WITHDRAWAL_STATUS_PENDING",
		2: "WITHDRAWAL_STATUS_PROCESSING",
		3: "WITHDRAWAL_STATUS_PROCESSED",
		4: "WITHDRAWAL_STATUS_FAILED",
		5: "WITHDRAWAL_STATUS_INVALID",
	}
	WithdrawalStatus_value = map[string]int32{
		"WITHDRAWAL_STATUS_UNSPECIFIED": 0,
		"WITHDRAWAL_STATUS_PENDING":     1,
		"WITHDRAWAL_STATUS_PROCESSING":  2,
		"WITHDRAWAL_STATUS_PROCESSED":   3,
		"WITHDRAWAL_STATUS_FAILED":      4,
		"WITHDRAWAL_STATUS_INVALID":     5,
	}
)

func (x WithdrawalStatus) Enum() *WithdrawalStatus {
	p := new(WithdrawalStatus)
	*p = x
	return p
}

func (x WithdrawalStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WithdrawalStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_deposit_proto_enumTypes[0].Descriptor()
}

func (WithdrawalStatus) Type() protoreflect.EnumType {
	return &file_deposit_proto_enumTypes[0]
}

func (x WithdrawalStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WithdrawalStatus.Descriptor instead.
func (WithdrawalStatus) EnumDescriptor() ([]byte, []int) {
	return file_deposit_proto_rawDescGZIP(), []int{0}
}

type DepositIdentifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	TxNonce       int64                  `protobuf:"varint,2,opt,name=tx_nonce,json=txNonce,proto3" json:"tx_nonce,omitempty"`
	ChainId       string                 `protobuf:"bytes,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositIdentifier) Reset() {
	*x = DepositIdentifier{}
	mi := &file_deposit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositIdentifier) ProtoMessage() {}

func (x *DepositIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositIdentifier.ProtoReflect.Descriptor instead.
func (*DepositIdentifier) Descriptor() ([]byte, []int) {
	return file_deposit_proto_rawDescGZIP(), []int{0}
}

func (x *DepositIdentifier) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *DepositIdentifier) GetTxNonce() int64 {
	if x != nil {
		return x.TxNonce
	}
	return 0
}

func (x *DepositIdentifier) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

var File_deposit_proto protoreflect.FileDescriptor

const file_deposit_proto_rawDesc = "" +
	"\n" +
	"\rdeposit.proto\x12\adeposit\"b\n" +
	"\x11DepositIdentifier\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12\x19\n" +
	"\btx_nonce\x18\x02 \x01(\x03R\atxNonce\x12\x19\n" +
	"\bchain_id\x18\x03 \x01(\tR\achainId*\xd4\x01\n" +
	"\x10WithdrawalStatus\x12!\n" +
	"\x1dWITHDRAWAL_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19WITHDRAWAL_STATUS_PENDING\x10\x01\x12 \n" +
	"\x1cWITHDRAWAL_STATUS_PROCESSING\x10\x02\x12\x1f\n" +
	"\x1bWITHDRAWAL_STATUS_PROCESSED\x10\x03\x12\x1c\n" +
	"\x18WITHDRAWAL_STATUS_FAILED\x10\x04\x12\x1d\n" +
	"\x19WITHDRAWAL_STATUS_INVALID\x10\x05B:Z8github.com/Bridgeless-Project/relayer-svc/internal/typesb\x06proto3"

var (
	file_deposit_proto_rawDescOnce sync.Once
	file_deposit_proto_rawDescData []byte
)

func file_deposit_proto_rawDescGZIP() []byte {
	file_deposit_proto_rawDescOnce.Do(func() {
		file_deposit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deposit_proto_rawDesc), len(file_deposit_proto_rawDesc)))
	})
	return file_deposit_proto_rawDescData
}

var file_deposit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_deposit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_deposit_proto_goTypes = []any{
	(WithdrawalStatus)(0),     // 0: deposit.WithdrawalStatus
	(*DepositIdentifier)(nil), // 1: deposit.DepositIdentifier
}
var file_deposit_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_deposit_proto_init() }
func file_deposit_proto_init() {
	if File_deposit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deposit_proto_rawDesc), len(file_deposit_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_deposit_proto_goTypes,
		DependencyIndexes: file_deposit_proto_depIdxs,
		EnumInfos:         file_deposit_proto_enumTypes,
		MessageInfos:      file_deposit_proto_msgTypes,
	}.Build()
	File_deposit_proto = out.File
	file_deposit_proto_goTypes = nil
	file_deposit_proto_depIdxs = nil
}
