// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api.proto

package types

import (
	types "github.com/Bridgeless-Project/relayer-svc/internal/types"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WithdrawalId  string                 `protobuf:"bytes,1,opt,name=withdrawal_id,json=withdrawalId,proto3" json:"withdrawal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitResponse) GetWithdrawalId() string {
	if x != nil {
		return x.WithdrawalId
	}
	return ""
}

type CheckWithdrawalResponse struct {
	state                protoimpl.MessageState      `protogen:"open.v1"`
	DepositIdentifier    *types.DepositIdentifier    `protobuf:"bytes,1,opt,name=deposit_identifier,json=depositIdentifier,proto3" json:"deposit_identifier,omitempty"`
	TransferData         *types.TransferData         `protobuf:"bytes,2,opt,name=transfer_data,json=transferData,proto3" json:"transfer_data,omitempty"`
	WithdrawalStatus     types.WithdrawalStatus      `protobuf:"varint,3,opt,name=withdrawal_status,json=withdrawalStatus,proto3,enum=deposit.WithdrawalStatus" json:"withdrawal_status,omitempty"`
	WithdrawalIdentifier *types.WithdrawalIdentifier `protobuf:"bytes,4,opt,name=withdrawal_identifier,json=withdrawalIdentifier,proto3" json:"withdrawal_identifier,omitempty"`
	Recovery             *types.Recovery             `protobuf:"bytes,5,opt,name=recovery,proto3" json:"recovery,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CheckWithdrawalResponse) Reset() {
	*x = CheckWithdrawalResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckWithdrawalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckWithdrawalResponse) ProtoMessage() {}

func (x *CheckWithdrawalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckWithdrawalResponse.ProtoReflect.Descriptor instead.
func (*CheckWithdrawalResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *CheckWithdrawalResponse) GetDepositIdentifier() *types.DepositIdentifier {
	if x != nil {
		return x.DepositIdentifier
	}
	return nil
}

func (x *CheckWithdrawalResponse) GetTransferData() *types.TransferData {
	if x != nil {
		return x.TransferData
	}
	return nil
}

func (x *CheckWithdrawalResponse) GetWithdrawalStatus() types.WithdrawalStatus {
	if x != nil {
		return x.WithdrawalStatus
	}
	return types.WithdrawalStatus(0)
}

func (x *CheckWithdrawalResponse) GetWithdrawalIdentifier() *types.WithdrawalIdentifier {
	if x != nil {
		return x.WithdrawalIdentifier
	}
	return nil
}

func (x *CheckWithdrawalResponse) GetRecovery() *types.Recovery {
	if x != nil {
		return x.Recovery
	}
	return nil
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19google/protobuf/any.proto\x1a\rdeposit.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"5\n" +
	"\x0eSubmitResponse\x12#\n" +
	"\rwithdrawal_id\x18\x01 \x01(\tR\fwithdrawalId\"\xeb\x02\n" +
	"\x17CheckWithdrawalResponse\x12I\n" +
	"\x12deposit_identifier\x18\x01 \x01(\v2\x1a.deposit.DepositIdentifierR\x11depositIdentifier\x12:\n" +
	"\rtransfer_data\x18\x02 \x01(\v2\x15.deposit.TransferDataR\ftransferData\x12F\n" +
	"\x11withdrawal_status\x18\x03 \x01(\x0e2\x19.deposit.WithdrawalStatusR\x10withdrawalStatus\x12R\n" +
	"\x15withdrawal_identifier\x18\x04 \x01(\v2\x1d.deposit.WithdrawalIdentifierR\x14withdrawalIdentifier\x12-\n" +
	"\brecovery\x18\x05 \x01(\v2\x11.deposit.RecoveryR\brecovery2\xae\x02\n" +
	"\x03API\x12Z\n" +
	"\x10SubmitWithdrawal\x12\x1a.deposit.DepositIdentifier\x1a\x16.google.protobuf.Empty\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/submit\x12{\n" +
	"\x0fCheckWithdrawal\x12\x1a.deposit.DepositIdentifier\x1a\x1c.api.CheckWithdrawalResponse\".\x82\xd3\xe4\x93\x02(\x12&/check/{chain_id}/{tx_hash}/{tx_nonce}\x12N\n" +
	"\vCheckHealth\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/healthB>Z<github.com/Bridgeless-Project/relayer-svc/internal/api/typesb\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_goTypes = []any{
	(*SubmitResponse)(nil),             // 0: api.SubmitResponse
	(*CheckWithdrawalResponse)(nil),    // 1: api.CheckWithdrawalResponse
	(*types.DepositIdentifier)(nil),    // 2: deposit.DepositIdentifier
	(*types.TransferData)(nil),         // 3: deposit.TransferData
	(types.WithdrawalStatus)(0),        // 4: deposit.WithdrawalStatus
	(*types.WithdrawalIdentifier)(nil), // 5: deposit.WithdrawalIdentifier
	(*types.Recovery)(nil),             // 6: deposit.Recovery
	(*emptypb.Empty)(nil),              // 7: google.protobuf.Empty
}
var file_api_proto_depIdxs = []int32{
	2, // 0: api.CheckWithdrawalResponse.deposit_identifier:type_name -> deposit.DepositIdentifier
	3, // 1: api.CheckWithdrawalResponse.transfer_data:type_name -> deposit.TransferData
	4, // 2: api.CheckWithdrawalResponse.withdrawal_status:type_name -> deposit.WithdrawalStatus
	5, // 3: api.CheckWithdrawalResponse.withdrawal_identifier:type_name -> deposit.WithdrawalIdentifier
	6, // 4: api.CheckWithdrawalResponse.recovery:type_name -> deposit.Recovery
	2, // 5: api.API.SubmitWithdrawal:input_type -> deposit.DepositIdentifier
	2, // 6: api.API.CheckWithdrawal:input_type -> deposit.DepositIdentifier
	7, // 7: api.API.CheckHealth:input_type -> google.protobuf.Empty
	7, // 8: api.API.SubmitWithdrawal:output_type -> google.protobuf.Empty
	1, // 9: api.API.CheckWithdrawal:output_type -> api.CheckWithdrawalResponse
	7, // 10: api.API.CheckHealth:output_type -> google.protobuf.Empty
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
